- name: Create application user
  mysql_user: 
    name: "{{ dbuser }}"
    password: "{{ dbpassword }}"
    priv: '*.*:ALL' 
    state: present
    host: "{{ host_ip }}"
    login_host: "{{ host_ip }}"
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"