- name: Sending notification email        
  mail:
    host: "{{ email_host }}"
    port: "{{ email_port }}"
    username: "{{ email_username }}"
    password: "{{ email_password }}"
    from: "{{ email_username }}"
    to:
    - rodel.paco@gmail.com
    - rodel.paco@webserverpage.com
    subject: MySQL Provisioning Report
    body: "All system has been successfully provisioned."
    secure: starttls
  delegate_to: localhost